### ISSUE TITLE
Validate execution points before setting them

### ISSUE THREAD

**Issue by RickMoynihan** [vvvvalvalval/scope-capture-nrepl#1]
I find I frequently make a typo, specifying an execution point that doesn't exist.  This causes all subsequent REPL interactions to be broken.

It would be good if when calling `(sc.nrepl.repl/in-ep 123)` that the function first checks that the execution point has already been captured.  

It might also be nice if `in-ep` would return a value indicating success or failure e.g.

```
user> (sc.nrepl.repl/in-ep 123) 
[:in-ep 123]
user> (sc.nrepl.repl/exit) 
[:exiting 123]
user> (sc.nrepl.repl/in-ep 123456) 
[:invalid-ep 123456]
```

**Comment by vvvvalvalval** [comment]
Thanks, I agree about the problem statement, but still have doubts about the proposed patch. I'd rather make this validation optional, as it may not be feasible in some (future) environments - e.g when using nREPL on top of [piggieback](https://github.com/nrepl/piggieback). It's probably not a problem currently as scope-capture-nrepl expects the middleware to run in the same address space as the REPL, but it may evolve to break this assumption.

I'll meditate on this for a few days then propose a change.

**Comment by RickMoynihan** [comment]
Interesting... I'd forgotten scope-capture also worked in clojurescript, though I don't know a huge amount about the cljs repl tooling landscape.

I see what you're saying about sharing the same address space though, as it's something I've been thinking a bit about in the context of my [nrebl.middleware](https://github.com/RickMoynihan/nrebl.middleware), which necessarily needs to work in process.  I hadn't appreciated that you'd given any thought to things being remote or in other environments etc.

If this is a concern, then I think a better solution might be to consolidate the various atoms (in particular `sc.nrepl.imp/current-ep-id` into `sc.impl.db/db`.  My original route of attack at solving this problem was to attach a `:validator` to the `atom`, so perhaps if all atoms were merged into the db we could fix this with a simple validation.

Consolidating atoms would also solve a potential concurrency bug that I noticed.  Which is that atoms are meant for un-coordinated synchronous change; but the validation of `current-ep-id` depends on the state in `sc.impl.db/db` so it's theoretically possible in the face of concurrent updates for invalid states to occur.  I was originally going to suggest switching the `atom`s for `ref`s, which would preserve the separation of concerns you have across modules and allow you to synchronise changes safely; however `ref`s aren't available in cljs (and couldn't coordinate across process boundaries anyway), so I think consolidation might be the most pragmatic option here.

The only other alternative I can think of would I think involve a communication protocol across processes, which feels like it would be brittle given the number of alternative possible environments.  I'm curious what options you had in mind.

**Comment by vvvvalvalval** [comment]
@RickMoynihan So I thought about it, and basically I think you're right:

* checking existence of EPs is a big improvement in ergonomics
* this library is mostly only suitable for projects where the nREPL middleware runs in the same process as the REPL (since that's where `in-ep` gets called anyway) - might as well make this constraint explicit, and maybe relax it in a future release ("provide more, require less").

So that's exactly what release `0.3.1` does, it's similar to [your PR](https://github.com/vvvvalvalval/scope-capture-nrepl/pull/6) but uses the public scope-capture API to check for existence.

Thanks for prompting these changes.
